### ISSUE TITLE
The Compile.cmd is not working?

### ISSUE THREAD

**Issue by Do-Your-Math** [hydrozoa-yt/pokemon#3]
When I open Compile.cmd, it says "'javac' is not recognized as an internal or external command,
operable program or batch file.
Press any key to continue . . .," and when I press a key, Compile.cmd closes. And since it closed the bin file was not created.

**Comment by hydrozoa-yt** [comment]
You have to have a JDK installed and available in your "Path" environment variable in order to use the "javac" command. Try Googling a bit, it's a common error when the JDK is not installed correctly.
